# Generated by Django 4.1.1 on 2022-10-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_img',
            field=models.ImageField(default='uploads/img_items/default_item_img.jpg', upload_to='uploads/img_items'),
        ),
    ]
