# Generated by Django 4.1.1 on 2022-10-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_img',
            field=models.ImageField(default='inventory/uploads/img_items/default_item_img.jpg', upload_to='inventory/uploads/img_items'),
        ),
    ]
