# Generated by Django 4.1.1 on 2022-10-03 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_img',
            field=models.ImageField(default='uploads/img_items/default_item_img.jpg', upload_to='uploads/img_items'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='subtotal',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
