# Generated by Django 4.1.1 on 2022-10-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_cartitem_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.inventory'),
            preserve_default=False,
        ),
    ]
