# Generated by Django 4.1.1 on 2022-10-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_cartitem_id_cartitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item_bought',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item_price',
        ),
    ]
