# Generated by Django 4.1.1 on 2022-10-05 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_cartitem_id_alter_cartitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_bought',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
