# Generated by Django 4.1.1 on 2022-10-05 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_cartitem_item_bought_cartitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='unit_price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
