# Generated by Django 4.1.1 on 2022-10-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_sales_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_img',
            field=models.ImageField(default='img_items/default_item_img.jpg', upload_to='img_items/'),
        ),
    ]
