# Generated by Django 4.1.1 on 2022-10-10 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_cartitem_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventory'),
        ),
    ]
