# Generated by Django 4.1.1 on 2022-10-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_cartitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
    ]
